### ISSUE TITLE
autogen.sh: removed call to mkdir -p m4

### ISSUE THREAD

**Issue by thchr** [stevengj/libctl#11]
When trying to run `autogen.sh` on a fresh clone of the libctl repo, I got multiple `aclocal: couldn't open directory 'm4': No such file or directory` errors. 

The issue seems to originate with line 17 of commit a7223a360fd82462756d2a9fb6e5047afd44f558, i.e. with the removal of `mkdir -p m4`. With this line reinstated `autogen.sh` executes without issue.

**Comment by stevengj** [comment]
Thanks, should be fixed now.

**Comment by thchr** [comment]
Great, thanks!
