### ISSUE TITLE
libctl.a and ctl.h no longer installed

### ISSUE THREAD

**Issue by steveweston** [stevengj/libctl#12]
It appears that libctl.a and ctl.h are no longer installed in version 4.0.0. I believe these are required by MPB, and so I am unable to get MPB to build, since it depends on libctl 4.0.0.

**Comment by stevengj** [comment]
They should still be installed, see:

https://github.com/stevengj/libctl/blob/master/src/Makefile.am#L4

Did you forget to set the CPPFLAGS to tell MPB where you installed libctl?  See http://mpb.readthedocs.io/en/latest/Installation/#installation-paths

**Comment by steveweston** [comment]
It turned out that the libctl configure script couldn't find Guile, so it didn't build libctl.a. When I initialized my environment properly, both libctl.a and ctl.h were properly built and installed. Thanks!

**Comment by stevengj** [comment]
Glad to hear it.

**Comment by stevengj** [comment]
Maybe we should print a bigger warning message if it can't find guile, or give an error unless you explicitly configure `--without-guile`.
