### ISSUE TITLE
code duplicated in ctl.h and ctl-math.h

### ISSUE THREAD

**Issue by HomerReid** [stevengj/libctl#5]
It looks like the new file `ctl-math.c` is a verbatim extraction of lines 119-399 from file `ctl.c,` intended to allow that code to be linked with the new guile-independent libctlgeom.

However, those lines are still present in `ctl.c`, which causes link errors when building libctl, i.e. 

```
/home/homer/work/Simpetus/libctl/src/ctl-math.c:237: multiple definition of `cnumber_equal'
.libs/ctl.o:/home/homer/work/Simpetus/libctl/src/ctl.c:323: first defined here
```

Probably your intention was either

(a) delete the lines in question from `ctl.c`, or 
(b) omit `ctl-math.c` from `libctl_la_SOURCES` in `src/Makefile.am`? 

@oskooi @christopherhogan

**Comment by stevengj** [comment]
My intention was to delete those lines from `ctl.c`, sorry; will fix shortly.
